spring:
  application:
    name: auth
  data:
    mongodb:
      uri: ${MONGO_DB_URI}
security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-expiration-time: ${JWT_ACCESS_EXPIRATION_TIME}
    refresh-expiration-time: ${JWT_REFRESH_EXPIRATION_TIME}