spring:
  application:
    name: main
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  data:
    mongodb:
      uri: ${MONGO_DB_URI}
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 5MB
security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-expiration-time: ${JWT_ACCESS_EXPIRATION_TIME}
    refresh-expiration-time: ${JWT_REFRESH_EXPIRATION_TIME}
server:
  error:
    whitelabel:
      enabled: false
